name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: ['8', '9', '10']
        php: ['7.4', '8.0', '8.1', '8.2']
        exclude:
          - { laravel: '9', php: '7.4' }
          - { laravel: '10', php: '7.4' },
          - { laravel: '10', php: '8.0' }

    name: PHP ${{ matrix.php }} Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          coverage: pcov

      - name: Install PHP Dependencies
        uses: nick-invision/retry@v2.8.2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover clover.xml

      - name: Check code coverage
        uses: codecov/codecov-action@v3
        if: "matrix.php == '8.1' && matrix.laravel == '9'"
